### ISSUE TITLE
UnsupportedOperationException with 2019.2

### ISSUE THREAD

**Issue by josephglanville** [databricks/intellij-jsonnet#14]
```
java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractList.add(AbstractList.java:153)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at com.jsonnetplugin.JsonnetCompletionContributor$1.addCompletions(JsonnetCompletionContributor.java:54)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:40)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:150)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:63)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:148)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:141)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:77)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:40)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:150)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:63)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:119)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:55)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:824)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:809)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$5(CodeCompletionHandlerBase.java:325)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$6(CodeCompletionHandlerBase.java:317)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by qeqar** [comment]
Ok the problem still exists.

Plugin version: 0.5
Idea version: IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 24, 2019

Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.7-arch1-1-ARCH
GC: ParNew, ConcurrentMarkSweep
Memory: 1894M
Cores: 12
Registry: 
Non-Bundled Plugins: Key Promoter X, com.databricks, Jetbrains TeamCity Plugin, com.intellij.plugins.watcher, name.kropp.intellij.makefile, org.intellij.plugins.hcl, org.jetbrains.plugins.go-template, Karma, org.jetbrains.plugins.go, com.intellij.kubernetes, com.vladsch.idea.multimarkdown, org.sonarlint.idea, org.toml.lang


can i do something to help debugging?

**Comment by josephglanville** [comment]
I think it just needs to be compiled against a more recent IDEA distribution and uploaded.
For now I have updated my fork here https://github.com/josephglanville/intellij-jsonnet but I don't publish it to the plugin repository so you will need to build and install it locally.

**Comment by qeqar** [comment]
mhh, ok the build is not working and throw a error that, according to jetbrains is fixed. 

but i knowledge is not good enough to fix it.
so i need to wait for the next databricks release

**Comment by josephglanville** [comment]
You probably need to set the project SDK to the IDEA Platform SDK rather than some random JDK on your machine.

**Comment by qeqar** [comment]
@lihaoyi-databricks i have the same errors with the new verison 0.7

**Comment by lihaoyi-databricks** [comment]
I've seen this randomly, but haven't managed to reliably reproduce. Any one of you want to submit a PR to fix it? Should just need to copy the list to a new list before adding stuff to it

**Comment by qeqar** [comment]
In general yes, but i don't have the knowledge to fix it.

**Comment by qeqar** [comment]
any hints were to look?

**Comment by lihaoyi-databricks** [comment]
@qeqar should be this line in the stack trace `JsonnetCompletionContributor.java:54`

It's adding to a `java.util.List` it received from the IntelliJ AST API, and apparently sometimes the list cannot be added to. Copying the elements to our own list that we instantiate ourselves before adding the elements should fix the crash

**Comment by qeqar** [comment]
sorry did not understand enough to fix it.

but it mostly happen on completion when the object is imported.

local openshift = import "../lib/openshift.libsonnet"; 
then openshift. and it throw the error

maybe that helps?
